### ISSUE TITLE
Investigate package cycles in lending 

### ISSUE THREAD

**Issue by pilloPl** [ddd-by-examples/library#19]

**Comment by bslota** [comment]
![55835239-effb9e00-5b1b-11e9-870d-6af17b2efab7](https://user-images.githubusercontent.com/22646896/56382096-dabaf980-6216-11e9-94c8-557e347b0133.png)
Problematic dependencies include: events, PatronId, book types

**Comment by bslota** [comment]
Answering your question @dosdebug regarding the cycles, it is true that conceptually a `patron` can hold (among others) a `book`, and a `book` can be held by a `patron`. What event storming sessions has uncovered, though, is that it is the `patron` that we're interacting with directly in order to place a book on hold, collect it, etc. It means that there is a relation: `patron` -> `book` which is unidirectional. In other words, a `patron` depends on a `book`, and this dependency should be reflected in the code as well.

Considering it further, having bidirectional dependencies, including `PatronEvents`, `PatronId`, `BookType`, we introduce coupling, loosing orthogonal package structure, components' autonomy, etc.

Does this sound reasonable?

I already started analysis with ArchUnit test (actually, I could put in into some branch to share with you - will do it soon) which shows all cycle-related issues. There are a couple of ways of solving them, and we need to align it with our model to keep arch-code gap minimized.

As soon as I push the branch with mentioned test, we can continue with it.

**Comment by dosdebug** [comment]
@bslota Sure. I got it, so we need to maintain uni-directional communication.
