### ISSUE TITLE
Checkout naming clarification

### ISSUE THREAD

**Issue by pilloPl** [ddd-by-examples/library#22]

**Comment by dosdebug** [comment]
@pilloPl What do you propose?

**Comment by bslota** [comment]
The reason for this issue to be opened is a confusion we faced at some point. Let me describe it. It was hard for me to distinguish notions of `collect`, `checkout` and `return`.  It turned out to mess our discussions, so we finally found some sources that clearly state, that in the context of book lending, libraries, the `checkout` is actually equal to `collect` (go to the library, take the book, go home), not to `return` as one (including me) could think. Regarding the code, `checkout` is used properly, but I believe we should get rid of the `collect` part both from model and from code, replacing any occurrence with word `checkout`. @pilloPl please correct me if I'm wrong

**Comment by dosdebug** [comment]
@bslota Okay, so if @pilloPl approves, I will be working on this.

**Comment by dosdebug** [comment]
@bslota @pilloPl Here is the PR https://github.com/ddd-by-examples/library/pull/27 for required changes.

All integration & unit tests are passing.

**Comment by dosdebug** [comment]
@bslota @pilloPl Conflicts are resolved and PR is updated. Please review.
